### ISSUE TITLE
Output URL includes locale for multi-lingual setup

### ISSUE THREAD

**Issue by nickdunn** [carlcs/craft-revmanifest#1]
When Craft is running with multiple locales on the frontend, the call to `UrlHelper::getUrl` will return the asset URLs including the current locale. This generally yields 404s because assets themselves won't live in translated folders.

e.g. `/en-gb/assets/stylesheets/application.css` where the actual output should be `/assets/stylesheets/application.css`

I can't see a simple way to remove the locale from the URL using native Craft methods. 

Any idea?

**Comment by carlcs** [comment]
The plugin shouldn’t be using that helper function at all, so removing the locales part wouldn’t be necessary.

I wrote the plugin as a quick solution when there wasn’t alternatives available. Since then the popular plugin https://github.com/clubstudioltd/craft-asset-rev got improved and allows to be configured for probably any directory setup via a config file. I have to admit that I use it myself and kind of abondonded this plugin here, but if you’d like to use it make a pull request that adds path configurations. Happy to accept this and maybe you get me to switch back!

**Comment by nickdunn** [comment]
Thanks for your honesty and a pointer to the other repo. I've installed it and it's working well, so I'm going to stick with it too :-)
